library(photobiology)

rm(list = ls(pattern = "*"))
load(file = "raw.data/MayaMeasure/Lumitronix39W.cal.spcs.Rda")
LUMITRONIX_white.spct <- `full power DIM open.cal.spc`
if (is.old_spct(LUMITRONIX_white.spct)) upgrade_spct(LUMITRONIX_white.spct)
save(LUMITRONIX_white.spct, file = "data/LUMITRONIX.white.spct.rda")
rm(`full power DIM open.cal.spc`)
cat(comment(LUMITRONIX_white.spct))
cat(class(LUMITRONIX_white.spct), "/n/n")

load(file = "raw.data/MayaMeasure/uvmax1.cal.spcs.Rda")
UVMAX305.spct <- as.source_spct(uvmax305_10cm.cal.spc)
upgrade_spct(UVMAX305.spct)
cat(class(UVMAX305.spct), "/n/n")
UVMAX340.spct <- as.source_spct(uvmax340_10cm.cal.spc)
upgrade_spct(UVMAX340.spct)
cat(class(UVMAX340.spct), "/n/n")
save(UVMAX305.spct, file = "data/UVMAX305.spct.rda")
save(UVMAX340.spct, file = "data/UVMAX340.spct.rda")
